package servlet;
import javax.servlet.*; import javax.servlet.annotation.*; import javax.servlet.http.*; import java.io.*; import model.*; import service.UserService;
@WebServlet({"/register","/login","/logout","/profile-update","/admin-update-user","/delete-user","/create-subadmin"})
public class AuthServlet extends HttpServlet{private UserService service=new UserService();
 protected void doPost(HttpServletRequest req,HttpServletResponse res)throws ServletException,IOException{String path=req.getServletPath();
  if(path.equals("/register")){User u=new CustomerUser(req.getParameter("id"),req.getParameter("username"),req.getParameter("email"),req.getParameter("password"),req.getParameter("membershipType"),req.getParameter("nic"),req.getParameter("telephone")); boolean ok=service.registerCustomer(u); if(ok){req.getSession().setAttribute("account",u);res.sendRedirect("profile.jsp");}else res.sendRedirect("register.jsp?error=1");}
  else if(path.equals("/login")){User u=service.login(req.getParameter("username"),req.getParameter("password")); if(u!=null){req.getSession().setAttribute("account",u); if(u.getRole().equals("CUSTOMER"))res.sendRedirect("profile.jsp"); else res.sendRedirect("admin-dashboard.jsp");}else res.sendRedirect("login.jsp?error=1");}
  else if(path.equals("/profile-update")){HttpSession s=req.getSession(false); if(s==null||s.getAttribute("account")==null){res.sendRedirect("login.jsp");return;} User old=(User)s.getAttribute("account"); User u=old.getRole().equals("CUSTOMER")?new CustomerUser(old.getId(),old.getUsername(),req.getParameter("email"),req.getParameter("password"),req.getParameter("membershipType"),req.getParameter("nic"),req.getParameter("telephone")):new AdminUser(old.getId(),old.getUsername(),req.getParameter("email"),req.getParameter("password"),old.getMembershipType(),old.getRole(),req.getParameter("nic"),req.getParameter("telephone")); service.updateUser(u); s.setAttribute("account",u); res.sendRedirect((u.getRole().equals("CUSTOMER")?"profile.jsp":"admin-profile.jsp")+"?updated=1");}
  else if(path.equals("/admin-update-user")){User admin=(User)req.getSession().getAttribute("account"); if(admin==null||admin.getRole().equals("CUSTOMER")){res.sendRedirect("login.jsp");return;} String role=req.getParameter("role"); User u=role.equals("SUB_ADMIN")?new AdminUser(req.getParameter("id"),req.getParameter("username"),req.getParameter("email"),req.getParameter("password"),"Admin","SUB_ADMIN",req.getParameter("nic"),req.getParameter("telephone")):new CustomerUser(req.getParameter("id"),req.getParameter("username"),req.getParameter("email"),req.getParameter("password"),req.getParameter("membershipType"),req.getParameter("nic"),req.getParameter("telephone")); service.updateUser(u); res.sendRedirect("manage-users.jsp?updated=1");}
  else if(path.equals("/delete-user")){HttpSession s=req.getSession(false); User acc=s==null?null:(User)s.getAttribute("account"); boolean head=acc!=null&&acc.getRole().equals("HEAD_ADMIN"); String id=req.getParameter("id"); service.deleteUser(id,head); if(acc!=null&&acc.getId().equals(id)){s.invalidate();res.sendRedirect("login.jsp?deleted=1");return;} res.sendRedirect("manage-users.jsp?deleted=1");}
  else if(path.equals("/create-subadmin")){User admin=(User)req.getSession().getAttribute("account"); if(admin==null||!admin.getRole().equals("HEAD_ADMIN")){res.sendRedirect("admin-dashboard.jsp?noaccess=1");return;} User u=new AdminUser(req.getParameter("id"),req.getParameter("username"),req.getParameter("email"),req.getParameter("password"),"Admin","SUB_ADMIN",req.getParameter("nic"),req.getParameter("telephone")); boolean ok=service.registerSubAdmin(u); res.sendRedirect("manage-users.jsp?subadmin="+(ok?"1":"0"));}
 }
 protected void doGet(HttpServletRequest req,HttpServletResponse res)throws ServletException,IOException{if(req.getServletPath().equals("/logout")){HttpSession s=req.getSession(false); if(s!=null)s.invalidate(); res.sendRedirect("index.jsp");}}
}
