package servlet;
import javax.servlet.*; import javax.servlet.annotation.*; import javax.servlet.http.*; import java.io.*; import model.*; import service.*;
@WebServlet({"/add-package","/customize-package","/delete-package","/add-price","/update-price","/delete-price"})
public class PackageServlet extends HttpServlet{private PackageService service=new PackageService(); private PriceListService prices=new PriceListService();
 protected void doPost(HttpServletRequest req,HttpServletResponse res)throws ServletException,IOException{String p=req.getServletPath(); User acc=(User)req.getSession().getAttribute("account");
  if(p.equals("/add-package")){if(acc==null||acc.getRole().equals("CUSTOMER")){res.sendRedirect("login.jsp");return;} service.addStandard(new StandardPackage(req.getParameter("id"),req.getParameter("name"),req.getParameter("destination"),Integer.parseInt(req.getParameter("duration")),Double.parseDouble(req.getParameter("basePrice")),Double.parseDouble(req.getParameter("discount")),req.getParameter("description")));res.sendRedirect("packages.jsp?added=1");}
  else if(p.equals("/customize-package")){if(acc==null||!acc.getRole().equals("CUSTOMER")){res.sendRedirect("login.jsp");return;} String hotel=req.getParameter("hotel"), transport=req.getParameter("transport"), activity=req.getParameter("activity"); String[] h=prices.find("HOTEL",hotel), t=prices.find("TRANSPORT",transport), a=prices.find("ACTIVITY",activity); service.addCustom(new CustomPackage(req.getParameter("id"),acc.getUsername(),req.getParameter("destination"),Integer.parseInt(req.getParameter("duration")),hotel,Double.parseDouble(h[2]),transport,Double.parseDouble(t[2]),activity,Double.parseDouble(a[2]),0,Integer.parseInt(req.getParameter("persons"))));res.sendRedirect("packages.jsp?custom=1");}
  else if(p.equals("/delete-package")){service.deleteStandard(req.getParameter("id"));res.sendRedirect("packages.jsp?deleted=1");}
  else if(p.equals("/add-price")){if(acc==null||acc.getRole().equals("CUSTOMER")){res.sendRedirect("login.jsp");return;} prices.add(req.getParameter("type"),req.getParameter("name"),Double.parseDouble(req.getParameter("price")));res.sendRedirect("price-list.jsp?added=1");}
  else if(p.equals("/update-price")){if(acc==null||acc.getRole().equals("CUSTOMER")){res.sendRedirect("login.jsp");return;} prices.update(req.getParameter("type"),req.getParameter("oldName"),req.getParameter("name"),Double.parseDouble(req.getParameter("price")));res.sendRedirect("price-list.jsp?updated=1");}
  else if(p.equals("/delete-price")){if(acc==null||acc.getRole().equals("CUSTOMER")){res.sendRedirect("login.jsp");return;} prices.delete(req.getParameter("type"),req.getParameter("name"));res.sendRedirect("price-list.jsp?deleted=1");}
 }}
