package servlet;
import javax.servlet.*; import javax.servlet.annotation.*; import javax.servlet.http.*; import java.io.*; import model.*; import service.*; import util.FileUtil;
@WebServlet({"/make-payment","/validate-payment","/delete-rejected-payment"}) @MultipartConfig
public class PaymentServlet extends HttpServlet{private PaymentService ps=new PaymentService(); private BookingService bs=new BookingService(); private NotificationService ns=new NotificationService();
 protected void doPost(HttpServletRequest req,HttpServletResponse res)throws ServletException,IOException{String path=req.getServletPath(); User acc=(User)req.getSession().getAttribute("account"); if(acc==null){res.sendRedirect("login.jsp");return;}
  if(path.equals("/make-payment")){if(!acc.getRole().equals("CUSTOMER")){res.sendRedirect("payments.jsp");return;} String bid=req.getParameter("bookingId"); Booking b=bs.getById(bid); double amount=b==null?0:b.getAmount(); String slip="NoSlip"; Part part=req.getPart("slip"); if(part!=null&&part.getSize()>0){String original=new File(part.getSubmittedFileName()).getName(); slip=System.currentTimeMillis()+"_"+original; File dir=new File(FileUtil.folder()+"payment_slips"); if(!dir.exists())dir.mkdirs(); part.write(dir.getAbsolutePath()+File.separator+slip);} String method=req.getParameter("method"); Payment p=method.equals("CARD")?new CardPayment(req.getParameter("id"),acc.getUsername(),bid,amount,"PENDING",slip,"Waiting for admin validation"):new OnlinePayment(req.getParameter("id"),acc.getUsername(),bid,amount,"PENDING",slip,"Waiting for admin validation"); ps.add(p); bs.updateStatus(bid,"PENDING_PAYMENT_VALIDATION"); res.sendRedirect("payments.jsp?pending=1");}
  else if(path.equals("/validate-payment")){if(acc.getRole().equals("CUSTOMER")){res.sendRedirect("login.jsp");return;} String status=req.getParameter("status"); String paymentId=req.getParameter("id"); String note=req.getParameter("note"); Payment p=ps.getById(paymentId); ps.updateStatus(paymentId,status,note); if(p!=null){bs.updateStatus(p.getBookingId(),status.equals("APPROVED")?"CONFIRMED":"PAYMENT_REJECTED");
      String title=status.equals("APPROVED")?"Payment Approved":"Payment Rejected";
      String msg=status.equals("APPROVED")?"Your payment for booking "+p.getBookingId()+" was approved. Booking confirmed.":"Your payment for booking "+p.getBookingId()+" was rejected. Please try payment again. Note: "+note;
      ns.add(new Notification("N"+System.currentTimeMillis(),p.getUsername(),title,msg,"ACTIVE"));
    } res.sendRedirect("payments.jsp?validated=1");}
  else if(path.equals("/delete-rejected-payment")){if(acc.getRole().equals("CUSTOMER")){res.sendRedirect("login.jsp");return;} ps.deleteRejected(req.getParameter("id")); res.sendRedirect("payments.jsp?deleted=1");}
 }}
