package service;
import model.*; import util.FileUtil; import java.io.*; import java.time.LocalDate; import java.util.*;
public class BookingService{private static final String FILE=FileUtil.path("bookings.txt");
 public boolean add(Booking b){if(!b.isValidBooking())return false; try(BufferedWriter bw=new BufferedWriter(new FileWriter(FILE,true))){bw.write(b.toFileString());bw.newLine();return true;}catch(Exception e){e.printStackTrace();return false;}}
 public List<Booking> all(){List<Booking> l=new ArrayList<>(); File f=new File(FILE); if(!f.exists())return l; try(BufferedReader br=new BufferedReader(new FileReader(FILE))){String line; while((line=br.readLine())!=null){String[] d=line.split(",",-1); if(d.length==9)l.add(new Booking(d[0],d[1],d[2],d[3],d[4],d[5],Integer.parseInt(d[6]),Double.parseDouble(d[7]),d[8]));}}catch(Exception e){e.printStackTrace();}return l;}
 public Booking getById(String id){for(Booking b:all())if(b.getId().equals(id))return b;return null;} public List<Booking> search(String key,String username){if(key==null)key=""; key=key.toLowerCase(); List<Booking> out=new ArrayList<>(); for(Booking b:all()){boolean owner=username==null||username.isEmpty()||b.getUsername().equals(username); boolean hit=b.getId().toLowerCase().contains(key)||b.getPackageId().toLowerCase().contains(key)||b.getUsername().toLowerCase().contains(key); if(owner&&hit)out.add(b);} return out;}
 public boolean updateStatus(String id,String status){List<Booking> list=all(); try(BufferedWriter bw=new BufferedWriter(new FileWriter(FILE))){for(Booking b:list){if(b.getId().equals(id)) b=new Booking(b.getId(),b.getUsername(),b.getPackageId(),b.getPackageName(),b.getBookingDate(),b.getTravelDate(),b.getPersons(),b.getAmount(),status); bw.write(b.toFileString());bw.newLine();}return true;}catch(Exception e){e.printStackTrace();return false;}}
 public boolean updateBooking(String id,String travelDate,int persons,double amount){List<Booking> list=all(); try(BufferedWriter bw=new BufferedWriter(new FileWriter(FILE))){for(Booking b:list){if(b.getId().equals(id)) b=new Booking(b.getId(),b.getUsername(),b.getPackageId(),b.getPackageName(),b.getBookingDate(),travelDate,persons,amount,b.getStatus()); bw.write(b.toFileString());bw.newLine();}return true;}catch(Exception e){e.printStackTrace();return false;}}
 public boolean delete(String id){List<Booking> list=all(); try(BufferedWriter bw=new BufferedWriter(new FileWriter(FILE))){for(Booking b:list)if(!b.getId().equals(id)){bw.write(b.toFileString());bw.newLine();}return true;}catch(Exception e){e.printStackTrace();return false;}}
 public String today(){return LocalDate.now().toString();}
}
