package service;
import model.*; import util.FileUtil; import java.io.*; import java.util.*;
public class PackageService{private static final String STD=FileUtil.path("packages.txt"); private static final String CUSTOM=FileUtil.path("custom_packages.txt");
 public boolean addStandard(StandardPackage p){return append(STD,p.toFileString());} public boolean addCustom(CustomPackage p){return append(CUSTOM,p.toFileString());} private boolean append(String file,String line){try(BufferedWriter bw=new BufferedWriter(new FileWriter(file,true))){bw.write(line);bw.newLine();return true;}catch(Exception e){e.printStackTrace();return false;}}
 public List<StandardPackage> getStandardPackages(){List<StandardPackage> list=new ArrayList<>(); File f=new File(STD); if(!f.exists())return list; try(BufferedReader br=new BufferedReader(new FileReader(STD))){String line;while((line=br.readLine())!=null){String[] d=line.split(",",-1); if(d.length==7)list.add(new StandardPackage(d[0],d[1],d[2],Integer.parseInt(d[3]),Double.parseDouble(d[4]),Double.parseDouble(d[5]),d[6]));}}catch(Exception e){e.printStackTrace();}return list;}
 public List<CustomPackage> getCustomPackages(){List<CustomPackage> list=new ArrayList<>(); File f=new File(CUSTOM); if(!f.exists())return list; try(BufferedReader br=new BufferedReader(new FileReader(CUSTOM))){String line; while((line=br.readLine())!=null){String[] d=line.split(",",-1); if(d.length==13)list.add(new CustomPackage(d[0],d[1],d[3],Integer.parseInt(d[4]),d[5],Double.parseDouble(d[6]),d[7],Double.parseDouble(d[8]),d[9],Double.parseDouble(d[10]),Double.parseDouble(d[11]),Integer.parseInt(d[12])));}}catch(Exception e){e.printStackTrace();} return list;}
 public StandardPackage getStandardById(String id){for(StandardPackage p:getStandardPackages())if(p.getId().equals(id))return p;return null;} public CustomPackage getCustomById(String id){for(CustomPackage p:getCustomPackages())if(p.getId().equals(id))return p;return null;}
 public TravelPackage getAnyById(String id){StandardPackage s=getStandardById(id); if(s!=null)return s; return getCustomById(id);} public double priceFor(String packageId,int persons){TravelPackage p=getAnyById(packageId); if(p==null)return 0; if(p instanceof StandardPackage)return p.calculatePrice()*persons; return p.calculatePrice();}
 public boolean deleteStandard(String id){List<StandardPackage> list=getStandardPackages(); try(BufferedWriter bw=new BufferedWriter(new FileWriter(STD))){for(StandardPackage p:list)if(!p.getId().equals(id)){bw.write(p.toFileString());bw.newLine();}return true;}catch(Exception e){e.printStackTrace();return false;}}
 public List<StandardPackage> searchStandard(String key){if(key==null)key=""; key=key.toLowerCase(); List<StandardPackage> out=new ArrayList<>(); for(StandardPackage p:getStandardPackages()) if(p.getId().toLowerCase().contains(key)||p.getName().toLowerCase().contains(key)||p.getDestination().toLowerCase().contains(key)) out.add(p); return out;}
 public List<CustomPackage> searchCustom(String key,String username){if(key==null)key=""; key=key.toLowerCase(); List<CustomPackage> out=new ArrayList<>(); for(CustomPackage p:getCustomPackages()){boolean owner=username==null||username.isEmpty()||p.getUsername().equals(username); boolean hit=p.getId().toLowerCase().contains(key)||p.getDestination().toLowerCase().contains(key)||p.getUsername().toLowerCase().contains(key); if(owner&&hit)out.add(p);} return out;}
}
