package service;
import model.*; import util.FileUtil; import java.io.*; import java.util.*;
public class PaymentService{private static final String FILE=FileUtil.path("payments.txt");
 public boolean add(Payment p){if(!p.processPayment())return false; try(BufferedWriter bw=new BufferedWriter(new FileWriter(FILE,true))){bw.write(p.toFileString());bw.newLine();return true;}catch(Exception e){e.printStackTrace();return false;}}
 public List<Payment> all(){List<Payment> l=new ArrayList<>(); File f=new File(FILE); if(!f.exists())return l; try(BufferedReader br=new BufferedReader(new FileReader(FILE))){String line;while((line=br.readLine())!=null){String[] d=line.split(",",-1); if(d.length==8){if(d[4].equals("CARD"))l.add(new CardPayment(d[0],d[1],d[2],Double.parseDouble(d[3]),d[5],d[6],d[7])); else l.add(new OnlinePayment(d[0],d[1],d[2],Double.parseDouble(d[3]),d[5],d[6],d[7]));}}}catch(Exception e){e.printStackTrace();}return l;}
 public Payment getById(String id){for(Payment p:all())if(p.getId().equals(id))return p;return null;} public Payment getByBookingId(String bid){for(Payment p:all())if(p.getBookingId().equals(bid))return p;return null;}
 public List<Payment> search(String key,String username){if(key==null)key="";key=key.toLowerCase(); List<Payment> out=new ArrayList<>(); for(Payment p:all()){boolean owner=username==null||username.isEmpty()||p.getUsername().equals(username); boolean hit=p.getId().toLowerCase().contains(key)||p.getBookingId().toLowerCase().contains(key)||p.getUsername().toLowerCase().contains(key)||p.getStatus().toLowerCase().contains(key); if(owner&&hit)out.add(p);}return out;}
 public boolean updateStatus(String id,String status,String note){List<Payment> list=all(); try(BufferedWriter bw=new BufferedWriter(new FileWriter(FILE))){for(Payment p:list){if(p.getId().equals(id)){p=p.getMethod().equals("CARD")?new CardPayment(p.getId(),p.getUsername(),p.getBookingId(),p.getAmount(),status,p.getSlipFile(),note):new OnlinePayment(p.getId(),p.getUsername(),p.getBookingId(),p.getAmount(),status,p.getSlipFile(),note);} bw.write(p.toFileString());bw.newLine();}return true;}catch(Exception e){e.printStackTrace();return false;}}
 public boolean deleteRejected(String id){List<Payment> list=all(); try(BufferedWriter bw=new BufferedWriter(new FileWriter(FILE))){for(Payment p:list) if(!(p.getId().equals(id)&&p.getStatus().equals("REJECTED"))){bw.write(p.toFileString());bw.newLine();}return true;}catch(Exception e){e.printStackTrace();return false;}}
}
